create table public.user_settings (
  owner_key text primary key default 'solo',
  pushup_settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.pushup_days (
  owner_key text not null default 'solo',
  day date not null,
  reps integer not null check (reps >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (owner_key, day)
);

create table public.workout_days (
  id bigint generated by default as identity primary key,
  owner_key text not null default 'solo',
  day date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner_key, day)
);

create table public.workout_exercises (
  id bigint generated by default as identity primary key,
  workout_day_id bigint not null
    references public.workout_days(id)
    on delete cascade,
  sort_order integer not null check (sort_order >= 0),
  exercise_name text not null check (length(trim(exercise_name)) > 0),
  category text null,
  created_at timestamptz not null default now(),
  unique (workout_day_id, sort_order)
);

create table public.workout_sets (
  id bigint generated by default as identity primary key,
  workout_exercise_id bigint not null
    references public.workout_exercises(id)
    on delete cascade,
  sort_order integer not null check (sort_order >= 0),
  reps integer null check (reps is null or reps >= 0),
  weight numeric(8,2) null check (weight is null or weight >= 0),
  created_at timestamptz not null default now(),
  unique (workout_exercise_id, sort_order)
);

create index idx_workout_days_owner_key_day
  on public.workout_days (owner_key, day);

create index idx_workout_exercises_workout_day_id_sort_order
  on public.workout_exercises (workout_day_id, sort_order);

create index idx_workout_sets_workout_exercise_id_sort_order
  on public.workout_sets (workout_exercise_id, sort_order);

alter table public.user_settings enable row level security;
alter table public.pushup_days enable row level security;
alter table public.workout_days enable row level security;
alter table public.workout_exercises enable row level security;
alter table public.workout_sets enable row level security;
